version: "3.7"

services:
  mongo:
    image: mongo:7.0.5-jammy
    restart: always
    network_mode: "host"
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    tmpfs:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      resources:
        limits:
          cpus: "0.72"
          memory: "465MB"

  api01: &api
    image: luizgribeiro/rinha2:latest
    hostname: api01
    network_mode: "host"
    environment:
      HTTP_PORT: 8081
      MAX_POOL_SIZE: 350
      N_WORKERS: 100
      MIN_POOL_SIZE: 150
      IS_SEEDER: false
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"

  api02:
    <<: *api
    hostname: api02
    network_mode: "host"
    environment:
      IS_SEEDER: false
      HTTP_PORT: 8082
      MAX_POOL_SIZE: 350
      N_WORKERS: 100
      MIN_POOL_SIZE: 150

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: "host"
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.18"
          memory: "25MB"
