version: "3.7"

services:
  mongo:
    image: mongo:7.0.5-jammy
    restart: always
    network_mode: "host"
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "250MB"

  api01: &api
    image: luizgribeiro/rinha2:latest
    hostname: api01
    network_mode: "host"
    environment:
      HTTP_PORT: 8081
      MAX_POOL_SIZE: 128
      MIN_POOL_SIZE: 64
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  api02:
    <<: *api
    hostname: api02
    network_mode: "host"
    environment:
      HTTP_PORT: 8082
      MAX_POOL_SIZE: 128
      MIN_POOL_SIZE: 64

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: "host"
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "80MB"
